version: 0.2
env:
  parameter-store:
    pPushBullet: "pPushBullet"
    pTwitterAccessTokenKey: "pTwitterAccessTokenKey"
    pTwitterAccessTokenSecret: "pTwitterAccessTokenSecret"
    pTwitterConsumerKey: "pTwitterConsumerKey"
    pTwitterConsumerSecret: "pTwitterConsumerSecret"
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - sam build
      # Deploy packaged SAM template
      - sam deploy --stack-name 'BlinkSnap' --s3-bucket "blink-code-bucket" --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --parameter-overrides "ParameterKey=pTwitterAccessTokenKey,ParameterValue=$pTwitterAccessTokenKey ParameterKey=pTwitterAccessTokenSecret,ParameterValue=$pTwitterAccessTokenSecret ParameterKey=pTwitterConsumerKey,ParameterValue=$pTwitterConsumerKey ParameterKey=pTwitterConsumerSecret,ParameterValue=$pTwitterConsumerSecret"
  post_build:
    commands:
      # Send a Pushbullet notification about the update to the stack
      - curl --silent -u """$pPushBullet"":" -d type="note" -d body="Updated $stackName" -d title="AWS Codebuild" 'https://api.pushbullet.com/v2/pushes'
