AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  BlinkSnap

Parameters:
  pTwitterConsumerKey:
    Type: String
    Description: The Twitter Consumer Key (Get this from the Twitter Developer Dashboard)
  pTwitterConsumerSecret:
    Type: String
    Description: The Twitter Consumer Secret (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenKey:
    Type: String
    Description: The Twitter Access Token Key (Get this from the Twitter Developer Dashboard)
  pTwitterAccessTokenSecret:
    Type: String
    Description: The Twitter Access Token Secret (Get this from the Twitter Developer Dashboard)

Resources:
  BlinkSnapFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/snap/
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Timeout: 30
      Environment:
        Variables:
          outputBucket: !Ref BlinkOutputBucket
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: 
                !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref BlinkOutputBucket
                    - '/*'
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:PutParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/BlinkCreds"
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 9-17 ? * MON-FRI *)
  
  BlinkSnapMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/movie/
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Timeout: 300
      Environment:
        Variables:
          outputBucket: !Ref BlinkOutputBucket
          twitterConsumerKey: !Ref pTwitterConsumerKey
          twitterConsumerSecret: !Ref pTwitterConsumerSecret
          twitterAccessTokenKey: !Ref pTwitterAccessTokenKey
          twitterAccessTokenSecret: !Ref pTwitterAccessTokenSecret
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:ListBucket
                - s3:GetBucketLocation
              Resource: 
                - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref BlinkOutputBucket
                      - '/*'
                - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref BlinkOutputBucket
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(5 17 ? * FRI *)
              
  BlinkOutputBucket:
    Type: AWS::S3::Bucket
    
Outputs:
  OutputBucketArn:
    Description: "Blink Output Bucket"
    Value: !GetAtt BlinkOutputBucket.Arn
